version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.1
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - 9200:9200
  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.1
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch