name: "PR Template"
about: 작업이 일단락 되었읍니다
title: 'Pull Request'
labels: "\U0001F4D6 문서 작성"

body:
- type: markdown
  attributes:
    value: "고친 내용을 작성"
- type: markdown
  attributes:
    value: "추가적으로 알아야할 사항"
