version: '3.8'

services:
  tensorflow-serving:
    image: tensorflow/serving
    container_name: tensorflow_serving
    ports:
      - "8501:8501"
    volumes:
      - ./:/Currency_Forecast 
    command: >
      --rest_api_port=8501
      --model_config_file=/Currency_Forecast/models.config
